language: node_js
sudo: false
node_js:
- '4.0'
- '0.10'
script: "./script/cibuild"
branches:
  only:
    - master
notifications:
  slack:
    secure: Gd35kJZntswKn7ilbJYm/AV4geDv7ajNia+ljCJUQ2taEMwKXpfRM0yWB3u8PJopnDGv29mESGP6SU+MJmg0oguynIYTLnqwF1A4gMwd/J3EQZdxW/AZ7r2jN1h4fh5sF1R+1f8m1NQoGu/pSZAp+Pzg8ejalvpz5j64V3ZTo7c=
