services:
  - postgresql
  - redis
language: ruby
cache: bundler
rvm:
- 2.3.1
bundler_args: "--without=development"
env:
  global:
    - DATABASE_URL=postgres://localhost/changeling_test
    - HTTP_BASIC_USERNAME=changeling
    - HTTP_BASIC_PASSWORD=password
before_script:
- psql -c 'create database changeling_test;' -U postgres
- bin/setup
script: bundle exec bin/cibuild
notifications:
  email: false
addons:
  postgresql: 9.4
