version: "2"
services:
  postgres:
    image: postgres:9.5.5-alpine
    expose:
      - "5432"
  redis:
    image: redis:3.2.4-alpine
    expose:
    - "6379"
  app:
    build: .
    environment:
      BIND: "0.0.0.0"
      PORT: "4000"
      REDIS_URL: "redis://redis:6379"
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_NAME: postgres
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
