version: "2"
services:
  app:
    build: .
    restart: always
    ports:
      - "8080:80"
    links:
      - db:db
    environment:
      - MYSQL_SERVER=db
      - MYSQL_DATABASE=teampass
      - MYSQL_PASSWORD=teampass
      - MYSQL_USER=teampass
      - CSRFP_TOKEN=sampletoken
      - SALT=samplesalt
  
  db:
    restart: always
    image: docker.dev.pardot.com/base/percona-server:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_DATABASE=teampass
      - MYSQL_PASSWORD=teampass
      - MYSQL_USER=teampass
