version: "2"
services:
  redis:
    image: docker.dev.pardot.com/base/pardot/redis
    expose:
      - "6379"
  app:
    build: .
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      LITA_ADAPTER: "blank"
    ports:
      - "8082:8080"
    volumes:
      - .:/app
    links:
      - redis
