---
apiVersion: v1
kind: ReplicationController
metadata:
  name: openflightsd
  labels:
    app: openflights
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openflights
    spec:
      containers:
      - name: openflightsd
        image: gcr.io/operator-europe-west/openflightsd:f98a386
        ports:
        - containerPort: 1747
