---
globals:
  global:
    dallas:
      host: mysql
      database: pardot_global
      username: boom
      password: town
shards:
  1:
    dallas:
      host: mysql
      database: pardot_shard1
      username: boom
      password: town
    seattle:
      host: mysql
      database: pardot_shard1
      username: boom
      password: town
  2:
    dallas:
      host: mysql
      database: pardot_shard1
      username: boom
      password: town
    seattle:
      host: mysql
      database: pardot_shard1
      username: boom
      password: town
...
