default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV.fetch('MYSQL_PORT_3306_TCP_ADDR', 'localhost') %>
  username: root
  password:

development:
  <<: *default
  database: canoe_development

test:
  <<: *default
  database: canoe_test

production: &production
  url: <%= ENV['DATABASE_URL'] %>
