default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
  username: <%= ENV.fetch("BOXEN_MYSQL_USER", "root") %>
  password:

development: &development
  <<: *default
  database: pardot_explorer_development

dallas_global:
  <<: *development
  database: pardot_global_test

test:
  <<: *development
  database: pardot_explorer_test

pardot_global_test:
  <<: *development
  database: pardot_global_test

pardot_shard1_test:
  <<: *development
  database: pardot_shard1_test

pardot_shard2_test:
  <<: *development
  database: pardot_shard2_test
