development: &development
  adapter: mysql2
  host: <%= ENV.fetch("BOXEN_MYSQL_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("BOXEN_MYSQL_PORT", 3306) %>
  username: <%= ENV.fetch("BOXEN_MYSQL_USER", "root") %>
  database: pardot_explorer_development

dallas_global:
  <<: *development
  database: test_pardot_global

test:
  <<: *development
  database: pardot_explorer_test

test_pardot_global:
  <<: *development
  database: test_pardot_global

test_pardot_shard1:
  <<: *development
  database: test_pardot_shard1

test_pardot_shard2:
  <<: *development
  database: test_pardot_shard2
