# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34c410c480af07c1548b5402a96ed80b2ce55ced1b226e4cd1f59fb5bfbc7c9faf2d0472ce8d319369efbdf52a7eb6be4ee4a1f27bd9bf3eb3b7f169ccad145e

test:
  secret_key_base: 19f4a25e78db595101fdc2495e09f7e0135937bec5488bbc3ae969f412106dc6ca34e4c68cb6cc1bfbd0cbb9736f0582010de15980a9a89df444dbddbf2beabb

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
