---
globals:
  global:
    local:
      1:
        host: mysql
        role: master
        database: pardot_global
        username: root
        password:
shards:
  1:
    local:
      1:
        host: mysql
        role: master
        database: pardot_shard1
        username: root
        password:
  2:
    local:
      1:
        host: mysql
        role: master
        database: pardot_shard2
        username: root
        password:
...
