---
globals:
  global:
    dfw:
      1:
        host: mysql
        database: pardot_global
        username: boom
        password: town
shards:
  1:
    dfw:
      1:
        host: mysql
        database: pardot_shard1
        username: boom
        password: town
    phx:
      1:
        host: mysql
        database: pardot_shard1
        username: boom
        password: town
  2:
    dfw:
      1:
        host: mysql
        database: pardot_shard1
        username: boom
        password: town
    phx:
      1:
        host: mysql
        database: pardot_shard1
        username: boom
        password: town
...
