---
globals:
  global:
    dfw:
      1:
        host: <%= ENV.fetch("DATABASE_HOST", "mysql") %>
        port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
        username: <%= ENV.fetch("DATABASE_USER", "root") %>
        password:
        database: pardot_global
    local:
      1:
        host: mysql
        port: 3306
        username: root
        password:
        database: pardot_global
shards:
  1:
    dfw:
      1:
        host: <%= ENV.fetch("DATABASE_HOST", "mysql") %>
        port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
        username: <%= ENV.fetch("DATABASE_USER", "root") %>
        password:
        database: pardot_shard1
    phx:
      1:
        host: mysql
        database: pardot_shard1
        username: boom
        password: town
  2:
    dfw:
      1:
        host: <%= ENV.fetch("DATABASE_HOST", "mysql") %>
        port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
        username: <%= ENV.fetch("DATABASE_USER", "root") %>
        password:
        database: pardot_shard1
    phx:
      1:
        host: mysql
        database: pardot_shard1
        username: boom
        password: town
...
