---
globals:
  global:
    dfw:
      1:
        host: mysql
        port: 3306
        username: root
        password:
        database: pardot_global
      2:
        host: mysql
        port: 3306
        username: root
        password:
        database: pardot_global_secondary
    local:
      1:
        host: mysql
        port: 3306
        username: root
        password:
        database: pardot_global
      2:
        host: <%= ENV.fetch("DATABASE_HOST", "mysql") %>
        port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
        username: <%= ENV.fetch("DATABASE_USER", "root") %>
        password:
        database: pardot_global
shards:
  1:
    phx:
      1:
        host: mysql
        username: boom
        password: town
        database: pardot_shard1
      2:
        host: mysql
        username: boom
        password: town
        database: pardot_shard1
    local:
      1:
        host: <%= ENV.fetch("DATABASE_HOST", "mysql") %>
        port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
        username: <%= ENV.fetch("DATABASE_USER", "root") %>
        password:
        database: pardot_shard1
      2:
        host: <%= ENV.fetch("DATABASE_HOST", "mysql") %>
        port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
        username: <%= ENV.fetch("DATABASE_USER", "root") %>
        password:
        database: pardot_shard1
  2:
    local:
      1:
        host: <%= ENV.fetch("DATABASE_HOST", "mysql") %>
        port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
        username: <%= ENV.fetch("DATABASE_USER", "root") %>
        password:
        database: pardot_shard2
      2:
        host: <%= ENV.fetch("DATABASE_HOST", "mysql") %>
        port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
        username: <%= ENV.fetch("DATABASE_USER", "root") %>
        password:
        database: pardot_shard2
    dfw:
      1:
        host: mysql
        port: 3306
        username: user
        password:
        database: primary
      2:
        host: mysql
        port: 3306
        username: user
        password:
        database: secondary
...
