default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV.fetch("CANOE_DATABASE_HOST", ENV.fetch("DATABASE_HOST", "localhost")) %>
  port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
  username: root
  password:

development:
  <<: *default
  database: canoe_development

test:
  <<: *default
  database: canoe_test

production: &production
  url: <%= ENV['DATABASE_URL'] %>
