default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("MAX_THREADS", 5) %>
  host: <%= ENV.fetch("CANOE_DATABASE_HOST", ENV.fetch("DATABASE_HOST", "localhost")) %>
  port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
  username: root
  password:

development:
  <<: *default
  database: canoe_development

test:
  <<: *default
  database: canoe_test

production: &production
  pool: <%= ENV.fetch("MAX_THREADS", 5) %>
  url: <%= ENV['DATABASE_URL'] %>
  connect_timeout: 2
  read_timeout: 2
  write_timeout: 2
  checkout_timeout: 2
