---
apiVersion: v1
kind: ReplicationController
metadata:
  name: hubot
  labels:
    app: hubot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hubot
    spec:
      containers:
      - name: hubot
        image: gcr.io/dev-europe-west1/hubot:987aec5
        command: ["/hubot/bin/hubot-k8s"]
        volumeMounts:
        - name: secrets
          mountPath: "/secrets"
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: hubot
